#!/bin/sh
## cut_mail for cut_mail in /home/ronan/rendu/SHL_2016_shell
## 
## Made by Ronan Boiteau
## Login   <ronan.boiteau@epitech.net>
## 
## Started on  Mon Jan  2 13:28:35 2017 Ronan Boiteau
## Last update Mon Jan  2 13:53:43 2017 Ronan Boiteau
##

print_usage()
{
    >&2 echo "USAGE: $progname mbox destdir"
    exit 1
}

check_usage()
{
    readonly argc="$#"

    if (( "$argc" != 2 )) ; then
	print_usage
    fi
}

main()
{
    readonly progname="$0"

    check_usage "$@"
    exit 0
}

main "$@"
