#!/bin/sh
## db for db in /home/ronan/rendu/SHL_2016_shell
## 
## Made by Ronan Boiteau
## Login   <ronan.boiteau@epitech.net>
## 
## Started on  Tue Jan  3 23:37:22 2017 Ronan Boiteau
## Last update Tue Jan  3 23:39:58 2017 Ronan Boiteau
##

check_usage()
{
    readonly argc="$#"

    if [ "$argc" -ne 1 ] ; then
	>&2 echo "USAGE: $progname filename"
	>&2 echo "filename : line by line db file - each entry must be separated with a blank line"
	>&2 echo "result : 1 line by record, order by field name"
	exit 1
    fi
}

main()
{
    readonly progname="$0"

    check_usage "$@"
    exit 0
}

main "$@"
