#!/bin/sh
## factorial for factorial in /home/ronan/rendu/SHL_2016_shell
## 
## Made by Ronan Boiteau
## Login   <ronan.boiteau@epitech.net>
## 
## Started on  Mon Jan  2 17:36:13 2017 Ronan Boiteau
## Last update Tue Jan  3 12:00:03 2017 Ronan Boiteau
##

check_usage()
{
    readonly argc="$#"

    if [ "$argc" -ne 1 ] ; then
	>&2 echo "USAGE: $progname number"
	>&2 echo "Compute factorial of a number"
	exit 1
    fi

    echo "$1" | grep -qE "^[0-9]+$"
    if [ "$?" -ne 0 ] ; then
	>&2 echo "ERROR"
	exit 1
    fi
}

find_factorial()
{
    nbr=$1
    if [ "$nbr" -gt 20 ] ; then
	>&2 echo "ERROR"
	exit 1
    fi
    result=1
    while [ "$nbr" -gt 0 ] ; do
	result=$(( result * nbr ))
	nbr=`expr $nbr - 1`
    done
    echo $result
}

main()
{
    readonly progname="$0"

    check_usage "$@"
    find_factorial "$1"
    exit 0
}

main "$@"
