#!/bin/bash

_check_usage()
{
    readonly ARGC="$1"
    
    if (( "$ARGC" != 1 )) ; then
	echo "Usage: $PROGNAME [FILE|FOLDER]"
	exit 1
    fi
    return 0
}

_check_filepath()
{
    if [[ ! -d "$FILEPATH" ]] && [[ ! -f "$FILEPATH" ]] ; then
	echo "$PROGNAME: cannot encrypt ‘$FILEPATH’: No such file or directory"
	exit 1
    fi
    return 0
}

_check_read_permission()
{
    if [[ ! -r "$FILEPATH" ]] ; then
	echo "Cannot read ‘$FILEPATH’: Permission denied"
	exit 1
    fi
    return 0
}

main()
{
    _check_usage "$#"
    readonly FILEPATH="$1"
    _check_filepath "$FILEPATH"
    _check_read_permission "$FILEPATH"

    echo -e "Passphrase? \c"
    read PASSPHRASE

    7z a -tzip "-p$PASSPHRASE" -mem=AES256 "$1.zip" "$1"
    
    exit 0
}

readonly PROGNAME="my7zcrypt"
main "$@"
