#!/bin/sh
## primary for primary in /home/ronan/rendu/SHL_2016_shell
## 
## Made by Ronan Boiteau
## Login   <ronan.boiteau@epitech.net>
## 
## Started on  Mon Jan  2 14:04:10 2017 Ronan Boiteau
## Last update Mon Jan  2 16:22:36 2017 Ronan Boiteau
##

check_usage()
{
    readonly argc="$#"

    if (( "$argc" != 1 )) ; then
	>&2 echo "USAGE: $progname n"
	>&2 echo "Display n first primary number"
	exit 1
    fi

    echo "$1" | grep -qE "^[0-9]+$"
    if (( $? == 1 )) ; then
	>&2 echo "ERROR"
	exit 1
    fi
}

is_prime()
{
    nbr=$1
    idx=2
    while (( $idx < $nbr )) ; do
	if [ $(expr $nbr % $idx) -eq 0 ] ; then
            echo 0
	    return
	fi
	(( idx++ ))
    done
    echo 1
}

find_primary()
{
    nbr_prime=$1
    prime=0
    nbr=2
    while (( $prime < $nbr_prime )) ; do
	if (( $(is_prime $nbr) == 1 )) ; then
	    if (( $prime != 0 )) ; then
		echo -n " "
	    fi
	    echo -n "$nbr"
	    (( prime++ ))
	fi
	(( nbr++ ))
    done
    if (( $prime > 0 )) ; then
	echo
    fi
}

main()
{
    readonly progname="$0"

    check_usage "$@"
    find_primary "$1"
    exit 0
}

main "$@"
