#!/bin/sh
## replace for replace in /home/ronan/rendu/SHL_2016_shell
## 
## Made by Ronan Boiteau
## Login   <ronan.boiteau@epitech.net>
## 
## Started on  Mon Jan  2 16:03:32 2017 Ronan Boiteau
## Last update Mon Jan  2 16:05:32 2017 Ronan Boiteau
##

check_usage()
{
    readonly argc="$#"

    if (( "$argc" != 3 )) ; then
	>&2 echo "USAGE: $progname original_stringfile replace_stringfile file"
	>&2 echo "Replace in file each string of original_stringfile by replace_stringfile"
	exit 1
    fi
}

main()
{
    readonly progname="$0"

    check_usage "$@"
    
    exit 0
}

main "$@"
