#!/bin/bash

_check_usage()
{
    readonly ARGC="$1"
    
    if (( "$ARGC" != 1 )) ; then
 	echo "Usage: $PROGNAME [FILE|FOLDER]"
	exit 1
    fi
    return 0
}

_check_filepath()
{
    if [[ ! -f "$FILEPATH" ]] ; then
	echo "$PROGNAME: cannot encrypt ‘$FILEPATH’: No such file"
	if [[ -d "$1" ]] ; then
	    echo "$PROGNAME does not support directories at this time"
	fi
	exit 1
    fi
    return 0
}

main()
{
    _check_usage "$#"
    readonly FILEPATH="$1"
    _check_filepath "$FILEPATH"

    echo -e "How many passes? \c"
    read PASSES
    shred -vfuz --iterations=$PASSES "$1"

    exit 0
}

readonly PROGNAME="safe_erase"
main "$@"
