#!/bin/sh
## tree for tree in /home/ronan/rendu/SHL_2016_shell
## 
## Made by Ronan Boiteau
## Login   <ronan.boiteau@epitech.net>
## 
## Started on  Tue Jan  3 23:37:12 2017 Ronan Boiteau
## Last update Tue Jan  3 23:41:13 2017 Ronan Boiteau
##

check_usage()
{
    readonly argc="$#"

    if [ "$argc" -ne 1 ] ; then
	>&2 echo "USAGE: $progname DirName"
	exit 1
    fi
}

main()
{
    readonly progname="$0"

    check_usage "$@"
    exit 0
}

main "$@"
