#!/bin/sh
## factorial for factorial in /home/ronan/rendu/SHL_2016_shell
## 
## Made by Ronan Boiteau
## Login   <ronan.boiteau@epitech.net>
## 
## Started on  Mon Jan  2 17:36:13 2017 Ronan Boiteau
## Last update Mon Jan  2 18:30:29 2017 Ronan Boiteau
##

check_usage()
{
    readonly argc="$#"

    if (( "$argc" != 2 )) ; then
	>&2 echo "USAGE: $progname number"
	>&2 echo "Compute factorial of a number"
	exit 1
    fi
}

option_parser()
{
    pull="true"
    migrate="true"
    restart_only="false"
    
    while (( "$#" > 0 )) ; do
	arg="$1"
	case $arg in
	    "--commit")
		commit="$2"
		shift
		;;
	    "-r"|"--restart")
		restart_only="true"
		;;
	    "--help")
		print_help
		;;
	    *)
		>&2 echo "ERROR: $arg unknown option" # Check if option or arg
		exit 1
		;;
	esac
	shift
    done
}

main()
{
    readonly progname="$0"

    check_usage "$@"
    option_parser "$@"
    exit 0
}

main "$@"
