#!/bin/sh
## factorial for factorial in /home/ronan/rendu/SHL_2016_shell
## 
## Made by Ronan Boiteau
## Login   <ronan.boiteau@epitech.net>
## 
## Started on  Mon Jan  2 17:36:13 2017 Ronan Boiteau
## Last update Mon Jan  2 21:59:07 2017 Ronan Boiteau
##

print_usage()
{
    >&2 echo "USAGE: $progname -l -u"
    >&2 echo "-l : lowcase"
    >&2 echo "-u : upcase"
    exit 1
}

option_parser()
{
    mode="none"
    
    while (( "$#" > 0 )) ; do
	arg="$1"
	case $arg in
	    "-l")
		mode="lowcase"
		;;
	    "-u")
		mode="upcase"
		;;
	    "-*")
		>&2 echo "ERROR: $arg unknown option"
		exit 1
		;;
	    *)
		print_usage
		;;
	esac
	shift
    done
}

main()
{
    readonly progname="$0"

    option_parser "$@"
    if [ "$mode" = "none" ] ; then
	print_usage
    fi
    exit 0
}

main "$@"
